ARG BASEIMAGEREGISTRY=""
FROM ${BASEIMAGEREGISTRY}openjdk:17-slim

RUN apt-get -y update && \
    apt-get install -y curl && \
    apt-get install -y wget && \
    apt-get install -y unzip

COPY target/*.jar /application.jar

RUN groupadd -g 1001 appuser && useradd -r -u 1001 -g appuser appuser
USER appuser

ENTRYPOINT ["java", "--enable-preview", "-jar", "/application.jar"]
